MLH-Fellowship/fellow-central

.github/config.yml, .github/stale.yml, .gitpod.yml
Add config for following bots:
- Welcome bot
- Slate bot
- Gitpod bot
=> feat: add github bots configs

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Adds CODE_OF_CONDUCT.md and CONTRIBUTING.md
=> feat: add code of conduct and contributing guide

backend/.gitignore, backend/README.md, backend/app.py, backend/requirements.txt
Initialized the backend Flask server with a hello world route
Fixes #2 
N/A
=> Initialize backend Flask server

backend/app.py, backend/requirements.txt
Please include a summary of the change and which issue is fixed. 
Added Discord OAuth and callback. Access token are stored in the user's session. Discord client ID and secret are stored in environment variables. All field needed for the User model are stored in appropriate variables: `email`, `username`, `discriminator` (the 4-digit number after the Discord username), `discord_id`, `in_fellowship` (boolean, True if user is in fellowship server, false otherwise.)
Please also include relevant motivation and context. 
Discord OAuth
List any dependencies that are required for this change.
`requests`
fixed #11 
N/A
=> added discord oauth and callback

backend/app.py
- Fixed duplicate user creation bug (oops)
- Return success instead of error if user is already registered and return the user info
N/A
=> Return success if user exists instead

backend/app.py
Added avatar url
fixed #44 
N/A
=> added avatar url from discord oauth

backend/app.py, backend/models.py, docs/endpoints.md
- Implemented get_user endpoint
Fixes #46 
Fixes #28 (if user is not registered, the api call will return success: false)
N/A
=> Implemented Get User route

frontend/src/components/DashboardPage.js, frontend/src/components/EventsPage.js, frontend/src/components/LoginPage.js, frontend/src/components/SendPointsPage.js, frontend/src/components/UserInfo.js, frontend/src/reducers/authReducer.js, frontend/src/sass/UserInfo.scss
Frontend fixes related to the newly added Get User route.
=> Get User after auth fix

CONTRIBUTING.md, README.md
Update main README.md with a lot of useful info.
=> feat (docs): update README.md

backend/app.py, docs/endpoints.md
Adds new dependencies to flask.send_file, and python.io. 
This PR will allow any authenticated admin to query details of a user and obtain the points of a user, hence fixing #34.
The get_user_image endpoint has also been added, which will obtain the image of an authenticated user only.
Fixes #54
Fixes #34
Also fixes #33
=> Implement Points view, and get user image view.

Procfile, backend/requirements.txt
Add Procfile (config file for deploy to heroku)
N/A
N/A
=> added Procfile for deployment

Procfile, backend/Procfile
Modify location of Procfile to backend
N/A
N/A
=> moved Procfile to backend directory

backend/app.py, docs/endpoints.md
Added get_events route
Fixes #31 
N/A
=> Implemented Get Events route

backend/app.py, docs/endpoints.md
=> Implemented /get_top_fellows endpoint

backend/app.py, docs/endpoints.md
=> Implemented /get_points_history endpoint

backend/app.py
Data is passed to the route with JSON data not as a form.
=> fix: create_event route

backend/app.py
=> fix: type error and json fix

backend/app.py
=> fix: api endpoint bug fixes

frontend/src/components/Button.js, frontend/src/components/DashboardPage.js, frontend/src/components/EventCard.js, frontend/src/components/EventsPage.js, frontend/src/components/LeaderboardPage.js, frontend/src/components/LoginPage.js, frontend/src/components/MainContent.js, frontend/src/components/ManageEventsPage.js, frontend/src/components/Nav.js, frontend/src/components/PointsHistoryPage.js, frontend/src/components/SendPointsPage.js, frontend/src/components/UserInfo.js, frontend/src/reducers/eventsReducer.js, frontend/src/sass/Button.scss, frontend/src/sass/LoginButton.scss
- Added points history page for fellow
- API integrations
#38
=> feat: Points History page

backend/app.py, docs/endpoints.md
Implement the get all pod points endpoint.
Fixes #62
N/A
=> Implement get all pod points endpoint

backend/app.py, backend/models.py
This changes the user model to account for the Discord avatar ID. Queries in reference to this have also been changed.
~~- I have made corresponding changes to the documentation~~
N/A
=> Fix Avatar not displaying correctly when querying user

backend/app.py
Fix issue where entries were being returned as lists.
N/A
=> fix user list issue

backend/app.py, docs/endpoints.md
=> Create route for total fellow count

frontend/src/components/AdminDashboardPage.js, frontend/src/components/DashboardPage.js, frontend/src/components/HighlightCard.js, frontend/src/components/LeaderboardPage.js, frontend/src/reducers/authReducer.js, frontend/src/sass/HighlightCard.scss
All essential API Endpoints integrated
Fixes #38 
=> API Endpoints integrated

backend/app.py, backend/models.py
@boyuan12 can you check if the endpoint response works for you?
For some reason if I change my avatar and re-register, I still get my old avatar.
Anyways this should make obtaining an avatar more generic.
N/A
=> Fix issue where user does not have custom avatar

discord-bot/bot.py
=> added discord bot file

backend/app.py
Fixed OAuth process, so if a role with < than 4 characters, it will work too.
N/A
=> check Pod in role name

backend/app.py
This *Should* fix situations where an admin attempts to obtain their user information, but in fact fails.
This will lead to the discord page looping (and hence not allowing admins to sign in!)
N/A
=> fix the admin user not working!

frontend/src/components/AdminDashboardPage.js, frontend/src/components/ManageEventsPage.js, frontend/src/components/SendPointsPage.js
Fix infinite loading when array empty
=> fix: infinite loading when array empty
